### ISSUE TITLE
Students can't register

### ISSUE THREAD

**Issue by estefaniamiguel** [mumuki/mumuki-classroom#115]
Do I have to register them all?
When I give them the link to register they see the following:
http://imgur.com/a/qk6mt

http://imgur.com/a/uhQsH

**Comment by aguspina** [comment]
Hey! Nowadays just the teacher can add students to the course.

**Comment by flbulgarelli** [comment]
Hi @estefaniamiguel 

This need further clarifications: 

1. historically Mumuki Classroom had an open-subscription model: you passed a link to your students and they entered the classroom to sign-up.
2. now the platform has moved to a closed-subscription model: you must explicitly add each of your students to your course, either one by one or in a bath using a CSV. 
  1. You can do it from here: http://<ORGANIZATION>.classroom.mumuki.io/#/courses/<COURSE>/guides
  1. Students can confirm or change their data when thy sign in for first time from laboratory - that is, they will never enter classroom again.  
3. there is severity usability issue with it since that link is not easy to find. 
    1. This issue has been already implemented in version 3.2 branch (https://github.com/mumuki/mumuki-classroom/commit/5219a12be62468108a9b44061b317827c0eab3b7) but is has not being release yet nor ported to master. 
   2. we are planning to deploy version 3.2 of the platform today to Ikumi servers, though, so you can expect this to be addressed in mumuki.io soon
3. we are planning to recover open-suscription mode, through the concept of invitation that you can create on demand. It is mostly done, but it is waiting this PR: https://github.com/mumuki/mumuki-laboratory/pull/767. We had little time to review it, though.  

I hope this helps understanding what is going on. 

Thanks for _mumukear_!
