### ISSUE TITLE
Specify the structure of the archive to upload

### ISSUE THREAD

**Issue by estefaniamiguel** [mumuki/mumuki-classroom#116]
On the screen: Alta masiva de estudiantes. I don't know the structure of the archive to upload. Also, I'm missing a button or something to upload. It only let me select the archive and do nothing else.

**Comment by estefaniamiguel** [comment]
Ok, it took some time and now I see a lot of columns with the name and e-mail to fill

**Comment by estefaniamiguel** [comment]
So: fixes

1. there should be a text saying what the structure is
2. there should be a loading after you selected your file

**Comment by flbulgarelli** [comment]
Agree.

**Comment by flbulgarelli** [comment]
Today I run into the same issue :disappointed:, and I didn't remember the file format. While we fix this issue, and for future reference, here there is an example: 

```csv
first_name,last_name,email
Jon,Doe,jondoe@mumuki.org
Mary,Doe,mary@mumuki.org
```

It must be a CSV, separated by commas, and with a header line.

**Comment by rodri042** [comment]
![screenshot5.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57a18889bbb1461300d0acef/125516c66e82c728ace21e0d46fb978826878dba87e6ab16e611b2843b492d762a10e17132d0bb7ebd412a070a5e4da8140d5d43fdf9897fa2e73572884e17ff933c0120996048e6edc00db513bb29814e80b5be8c4ac4e13e26e38a8b5d73.png)

There's already an example with the proper format. I think this issue is too old :P

**Comment by flbulgarelli** [comment]
Apparently somebody - @fedescarpa :roll_eyes: :stuck_out_tongue: - did not mark this issue as closed

**Comment by fedescarpa** [comment]
Puede ser :sweat_smile:
